# Generated by Django 3.2.9 on 2022-03-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('length', models.CharField(max_length=250)),
                ('weight', models.CharField(max_length=250)),
                ('lifespan', models.CharField(max_length=250)),
                ('habitat', models.CharField(max_length=250)),
                ('diet', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
